// <auto-generated />
using System;
using ConsultaAlertaDengue.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultaAlertaDengue.Infrastructure.Migrations
{
    [DbContext(typeof(ConsultaAlertaDengueDbContext))]
    [Migration("20250405232548_v0001")]
    partial class v0001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConsultaAlertaDengue.Domain.Entities.DadosDengue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("CasosEstimados")
                        .HasColumnType("DOUBLE")
                        .HasAnnotation("Relational:JsonPropertyName", "casos_est");

                    b.Property<int>("CasosNotificados")
                        .HasColumnType("INT")
                        .HasAnnotation("Relational:JsonPropertyName", "casos");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATE");

                    b.Property<int>("NivelAlerta")
                        .HasColumnType("INT")
                        .HasAnnotation("Relational:JsonPropertyName", "nivel");

                    b.Property<int>("SemanaEpidemiologica")
                        .HasColumnType("INT")
                        .HasAnnotation("Relational:JsonPropertyName", "SE");

                    b.HasKey("Id");

                    b.ToTable("DadosDengue", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
